### ISSUE TITLE
Code to generate LAL-randomtree-simulatedunbalanced-big.npz

### ISSUE THREAD

**Issue by kaushikpavani** [ksenia-konyushkova/LAL#2]
In file AL experiments.ipynb, the RF regressor is trained on data from the file 'LAL-randomtree-simulatedunbalanced-big.npz'. Where is the code to generate the npz file?

How can I generate my own data for the regressor?

**Comment by ksenia-konyushkova** [comment]
I have updated the repository to include folder ./LAL dataset generation/ with the code to generate that file. It is a draft of the code which I hope to improve later. Please notice, that depending on the amount of data that you want to generate, it might take a while (a few days even). However, all the components are there for your experimentation.

**Comment by kaushikpavani** [comment]
Thank you, much appreciated!
