### ISSUE TITLE
License for Repository

### ISSUE THREAD

**Issue by paulmorio** [ksenia-konyushkova/LAL#4]
Dear Dr. Konyushkova,

I am a research student and I would like to use some of the datasets as part of a research paper submission in active learning (of course citing this paper, and all of the related works). First off is this ok? Secondly, could you add an open source license to this repository as it seems to be the requirement nowadays for us to be able to use the assets and cite the work at in our submission?

Sincerely,
Paul Scherer

**Comment by ksenia-konyushkova** [comment]
Thanks for your interest in our work. Yes, of course you are welcome to use this repository. Some datasets are part of the repo and some are third party and you can find them cited in the paper. 
I have now added Apache 2 license as per your request. Good luck with your work!
